### PR TITLE
fix: upstream provider fixes

### LINKED ISSUE #697: Re-record PollyJS HTTP recordings
This is a scheduled reminder to re-record the PollyJS HTTP recordings used in
the tests.

# Why?

We use HTTP recordings to ensure fast, reliable and deterministic test and
CI results. However, as upstream services change their HTTP responses, our test
data becomes outdated and our tests may not uncover actual problems. Therefore,
these recordings should be recreated periodically, and unfortunately we don't
have an automated setup for this yet.

# How?

1. Remove `tests/test-data/__recordings__`
2. Run the tests again (`npm t`)
3. Commit the changes in `tests/test-data/__recordings__`

Thank you!

_:robot: Beep boop, this issue was filed automatically because of a scheduled CI job._

### PR DESCRIPTION
**Pull request by ROpdebee**
* Audiomack new layout
* Updated test URLs for booth.pm

Unfixed:
* DatPiff site is still down
* Amazon Audible audiobook redirection is broken. If I recall correctly, if we were given a product page for an Audible audiobook, we'd rewrite to an Audible-specific page to get higher resolution images. However, that URL rewrite now leads back to the Amazon main page, so we can't use that special case anymore. @kellnerd do you know what the new Audible URL should be (or of any other tricks)?

Closes #697

### CODE REVIEW

**Comment by kellnerd** [comment]
> However, that URL rewrite now leads back to the Amazon main page, so we can't use that special case anymore.

In which scenario does it redirect for you?
For me these `https://www.audible.com/hz/audible/mlp/mfpdp/` URLs are simply "Page not found" error pages now and in addition the ASINs for Audible are no longer the same as on Amazon. Our test case https://www.amazon.com/dp/B017WJ5PR4 corresponds to https://www.audible.com/pd/B017WJ5ZK6 for example.
Since that page also offers only the lousy 500x500 cover image we could skip this special handling completely. Unfortunately I haven't been able to extract any hires covers from Audible (or Amazon digital audiobooks) as of today (and haven't used it as a source for many months), so it might be no longer possible...

**Comment by ROpdebee** [comment]
I think we used to rewrite `https://www.amazon.com/dp/B017WJ5PR4` to `https://www.amazon.com/hz/audible/mlp/mfpdp/B017WJ5PR4` but that now redirects to `https://www.amazon.com/dp/B017WJ5PR4?ref=adbl_mfpdp_geo` again, at least for me. But if the cover art is limited to 500x500, I'll just remove the special case then.

**Comment by kellnerd** [comment]
> I think we used to rewrite https://www.amazon.com/dp/B017WJ5PR4 to https://www.amazon.com/hz/audible/mlp/mfpdp/B017WJ5PR4 but that now redirects to https://www.amazon.com/dp/B017WJ5PR4?ref=adbl_mfpdp_geo again, at least for me.

Oops, then I was imply teasting with the wrong domain yesterday. This link also redirects for me.

Interestingly, the [larger image from our Audible test case](https://m.media-amazon.com/images/I/91WJ0q27ddL.jpg) still exists, but there seems to be no way to extract the image identifier from anywhere...

**Comment by ROpdebee** [comment]
Hmm. Hopefully we find a way to extract those again later, but for now, it's better to have a 500x500 image than to have no image at all :)

**Comment by ROpdebee** [comment]
> Interestingly, the [larger image from our Audible test case](https://m.media-amazon.com/images/I/91WJ0q27ddL.jpg) still exists, but there seems to be no way to extract the image identifier from anywhere...

Funnily enough, in #786, I changed the image extraction logic to use that of the physical product pages, and the old images are now in use again 😅

**Pull request merged**
