### PR TITLE
fix(deps): downgrade babel-plugin-transform-async-to-promises to v0.8.16

### PR DESCRIPTION
**Pull request by kellnerd**
Reverts a536aefabbb10500137e68dc335c4ac27b51b521 to hotfix #351.
More notes why this has broken the build at https://github.com/ROpdebee/mb-userscripts/commit/3eacdad5e350196ac64f95627c07cbde342d4053.

### CODE REVIEW

**Comment by ROpdebee** [comment]
Did this actually fix it? I'm AFK so I can't test it myself (so thanks @kellnerd for the quick intervention!) but looking at the diff, I don't immediately understand how this upgrade could break anything... it looks like it just enforces a cast to a boolean.

If this didn't fix it, my guess would be the changes made to the async iterators in one of the linting commits. IIRC I added an explicit `return undefined` there, which could explain why `undefined` shows up there.

**Comment by kellnerd** [comment]
It did fix the problem, but I'll admit that I don't fully understand this myself. I think that https://github.com/ROpdebee/mb-userscripts/commit/3eacdad5e350196ac64f95627c07cbde342d4053#diff-bce89bee21387c71137058a0ed02c980600e5ea9ef86bf3fb16538231fff508aR2373 is supposed to return the value of `_iterator.next()` if the `_interrupt` and `_exit` flags are false but v0.8.17 tries to convert it into a Boolean with `!!_iterator.next()` . Also I have not found the root cause in the [babel plugin's changes](https://github.com/rpetrich/babel-plugin-transform-async-to-promises/compare/v0.8.16...v0.8.17) yet.

**Comment by ROpdebee** [comment]
Huh. It seems like there's some conflict between babel's regenerators and the plugin. If we disable regenetators, the plugin transforms the async generator and the `for await` statements itself. But if we enable babel's regenerator, babel transforms the generator and `for await` statements, and then the plugin does some more transformation, and that leads to some conflict...

**Pull request merged**
