### PR TITLE
feat(inline recs): Order tracks by ascending release dates

### PR DESCRIPTION
**Pull request by jesus2099**
For the moment, release tracks were displayed in random order.
Now they will be ordered by date, then title, then comment.

I have also added display of release comment and added release date as tooltip.

---

@ROpdebee, may I leave you manage the version number, OK?
My 3 concurrent PR have no conflict between themselves:

- This
- #776 
- #777

### CODE REVIEW

**Comment by jesus2099** [comment]
Hmm.
I see those 2 redundant commits have the same content but not the same ID.
I will try to make them disappear from this PR, as soon as I have time and PC again.

**Comment by jesus2099** [comment]
Super! I managed to repair my stuff, thanks to a PC with TortoiseGit ([requires admin rights](https://gitlab.com/tortoisegit/tortoisegit/-/issues/726)).

**Comment by jesus2099** [comment]
Ah, I should also add medium and track in the sort.

**Comment by jesus2099** [comment]
I have reset the version to previous value to avoid boring git conflicts with other PR.

Doing so, I noticed the `@exclude` rules were not working as intended and fixed them.
I have also added `musicbrainz.eu` support.

**Comment by jesus2099** [comment]
I renamed my commits to pass that test.

**Comment by jesus2099** [comment]
Ach, I cannot rephrase that last commit to start with "fix(inline recs):" add I'm on smartphone...

I have fixed the "not detecting video recordings" bug without breaking, without detecting recordings from online relationships, hopefully no other breakages. 

Release with video recordings: https://musicbrainz.org/release/0a5be94f-3429-46bd-9b1d-07dcb0209098

Release with recordings in inline relationships (on CD 23): https://musicbrainz.org/release/70dcde39-81ed-45e8-bdb3-f511112a3880

**Comment by jesus2099** [comment]
Maybe you'll prefer 3 separate PR.
I'll split it when I have a PC handy.

**Comment by jesus2099** [comment]
For sake of clarity, I have split this PR in 3:

- #764 
- #776
- #777

**Review by kellnerd — COMMENTED** [review]
I feel that it is a bit too hacky to inject an HTML comment into the DOM just for sorting purposes. It would be cleaner to sort the releases with a custom sorting function before mapping them to HTML with `formatRow`.

**Comment by jesus2099** [comment]
Ok, I will try to do that! 😉

**Comment by jesus2099** [comment]
Ok, I will try to do that! 😉

**Comment by jesus2099** [comment]
You were right, @kellnerd: With the sorting function, the code looks cleaner!

**Comment by jesus2099** [comment]
Would you like that I squash this into a single commit, before merge?

**Review by ROpdebee — CHANGES_REQUESTED** [review]
Thank you @jesus2099 for this and the other PRs, and thanks @kellnerd for reviewing and processing them while I'm pre-occupied! :heart:

Just a small nitpick: Could you also change the month in the version number? Other than that, LGTM.

@jesus2099 Don't bother squashing the commits, we'll do that when merging. 🙂

**Comment by jesus2099** [comment]
Oh you're right, I got the wrong date!
You're welcome @ROpdebee!
I hope your worries will be solved.

**Review by ROpdebee — APPROVED** [review]

**Pull request merged**
